services:
  - type: web
    name: apigas-laravel
    env: docker
    plan: free
    dockerfilePath: ./dockerfile
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://apigas-laravel.onrender.com
      - key: APP_KEY     # GENÉRALO UNA SOLA VEZ: `php artisan key:generate --show`
        value: base64:XXXXXXXXXXXX               # pega aquí el valor
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL     # Laravel parsea esta URL automáticamente
        fromDatabase:
          name: apigas-db
          property: connectionString

databases:
  - name: apigas-db
    plan: free
